### PR TITLE
Remove team alias and update footer (c)to 2020

### PR DESCRIPTION
**Pull request by dnsguru**
Addresses #23 and updates copyright notice to 2007-2020 from 2007-2016

### CODE REVIEW

**Comment by sleevi** [comment]
Thanks!

This mechanically looks correct, but one thing I couldn’t figure out when grepping is:
1. The JS functions don’t seem to be called
2. There doesn’t seem to be a link to the contact page

So these are good, but I’m not sure if I missed something basic and we can remove more?

**Comment by dnsguru** [comment]
I didn't see a place where those were used either.  Can I merge this and then we come back to that in 4 years? ;)

**Comment by sleevi** [comment]
:)

I’d much rather delete as much as possible. I’m more than happy to put together a PR for this, if that’s asking too much. It was just the end of the day and I was filing the issue so I wouldn’t forget. I figure a 404 would tell us sooner than later if we broke the wrong thing :)

**Comment by dnsguru** [comment]
Updated to pull the js code out.

Can you review?

ALSO: do we need @WilsonKathleen also in on this?  I'd had her listed but that might have been unnecessary

**Comment by WilsonKathleen** [comment]
> ALSO: do we need @WilsonKathleen also in on this?

Nope. Don't need me on the review list. Just Sleevi. Thanks!

**Comment by dnsguru** [comment]
Contact .... It (I think) is followed from old links

**Comment by weppos** [comment]
[/contact is indexed](https://www.google.com/search?q=site%3Apublicsuffix.org) so it was referenced somewhere. I could not find a link either.

I agree we can remove, given there's in homepage the reference to the ML.

**Comment by dnsguru** [comment]
I addressed everything but put re-review on sleevi - will undo that and merge

shame we can't 301 the contact/index.html -> /index.html

**Pull request merged**
